(function(){
'use strict';
var STORAGE_KEY='ppp_rl_planer_v16_2';
var loading=false,saveTimer=null,defaults=null,initDone=false;
function id(x){return document.getElementById(x)}
function clone(x){return JSON.parse(JSON.stringify(x))}
function addStyle(){if(id('v16-style'))return;var st=document.createElement('style');st.id='v16-style';st.textContent='.v16-acc-stack{display:flex;flex-direction:column;gap:12px;width:100%}.v16-acc{display:block;border:1px solid var(--line);border-radius:6px;background:rgba(255,255,255,.35);overflow:hidden;width:100%;margin:0}.v16-head{display:flex;align-items:center;justify-content:space-between;padding:11px 14px;cursor:pointer;background:var(--cream);font-family:Syne,sans-serif;font-weight:700;user-select:none}.v16-title{display:flex;gap:10px;align-items:center}.v16-arrow{display:inline-block;transition:transform .2s}.v16-acc.open .v16-arrow{transform:rotate(90deg)}.v16-body{display:none;padding:12px}.v16-acc.open .v16-body{display:block}.v16-stations{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:12px!important;width:100%!important}.psy-presets button.v16-base{background:var(--blue)!important;color:#fff!important;border-color:var(--blue)!important}.psy-presets button.v16-comp{background:#9b3f64!important;color:#fff!important;border-color:#9b3f64!important}.psy-presets button.v16-active{font-weight:700;box-shadow:0 0 0 3px rgba(45,105,155,.22),inset 0 -2px 0 rgba(0,0,0,.18)}.mw-v16{width:58px;text-align:right;padding:4px 5px;border:1px solid var(--line);border-radius:4px;background:#fff;font:inherit}.data-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.data-status{font-size:10px;color:rgba(28,28,46,.55);margin-left:auto}.btn-save{background:var(--blue);color:#fff;border-color:var(--blue)}.btn-export{background:var(--green);color:#fff;border-color:var(--green)}.btn-import{background:#7a4a8f;color:#fff;border-color:#7a4a8f}.btn-reset{background:#fff;color:var(--red);border-color:rgba(192,57,43,.45)}@media(max-width:1100px){.v16-stations{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:650px){.v16-stations{grid-template-columns:1fr!important}}';document.head.appendChild(st)}
function makeAcc(title,cards,open){var box=document.createElement('section');box.className='v16-acc'+(open?' open':'');var h=document.createElement('div');h.className='v16-head';h.setAttribute('role','button');h.setAttribute('tabindex','0');h.innerHTML='<div class="v16-title"><span class="v16-arrow">▶</span><span>'+title+'</span></div><span class="card-sub">'+cards.length+' Stationen</span>';var b=document.createElement('div');b.className='v16-body';var g=document.createElement('div');g.className='v16-stations';cards.forEach(function(c){g.appendChild(c)});b.appendChild(g);box.appendChild(h);box.appendChild(b);function toggle(){box.classList.toggle('open')}h.onclick=toggle;h.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}};return box}
function accordion(){var vs=id('vs-grid');if(!vs)return false;var cards=Array.prototype.slice.call(vs.querySelectorAll(':scope > .sta-card'));if(cards.length<16){cards=Array.prototype.slice.call(vs.children).filter(function(x){return x.classList&&x.classList.contains('sta-card')})}if(cards.length<16)return false;var stack=document.createElement('div');stack.className='v16-acc-stack';stack.appendChild(makeAcc('S1–S4 · Akutpsychiatrie',cards.slice(0,4),true));stack.appendChild(makeAcc('S5–S8 · Gerontopsychiatrie und Sucht',cards.slice(4,8),false));stack.appendChild(makeAcc('S9–S12 · Allgemeinpsychiatrie und Psychosomatik',cards.slice(8,12),false));stack.appendChild(makeAcc('S13–S16 · PK Fürth',cards.slice(12,16),false));vs.className='';vs.innerHTML='';vs.appendChild(stack);return true}
function ensureAccordion(){var tries=0;function run(){tries++;if(accordion())return;if(tries<40)setTimeout(run,100)}run()}
function removeScenarios(){var nav=document.querySelector('nav');if(nav){Array.prototype.slice.call(nav.querySelectorAll('button')).forEach(function(b){if((b.getAttribute('onclick')||'').indexOf("'sz'")>=0)b.remove()});var ps=Array.prototype.slice.call(nav.querySelectorAll('button')).filter(function(b){return(b.getAttribute('onclick')||'').indexOf("'psy'")>=0})[0];if(ps)ps.textContent='⑤ Psychosomatik'}var p=id('page-sz');if(p)p.remove()}
function setupWAN(){if(!BB.WAN)BB.WAN={grp:'A',name:'Warten auf Nachsorge',mw:BB.A1.mw.slice(),teil:false};if(VS_BBs.indexOf('WAN')<0)VS_BBs.unshift('WAN');KLINIK.vs.forEach(function(st,i){if(i===10||i===11){delete st.mix.WAN}else if(st.mix.WAN===undefined)st.mix.WAN=0})}
function rebuild(){if(typeof buildAllCards==='function')buildAllCards();var g2=KLINIK.vs[10],g3=KLINIK.vs[11];if(g2)delete g2.mix.WAN;if(g3)delete g3.mix.WAN;ensureAccordion()}
function ruleEditor(){var page=id('page-rl');if(!page)return;var table=page.querySelector('table'),body=table&&table.querySelector('tbody');if(!body)return;var cats=['A1','WAN','A2','A6','A7','A8','A9','S1','S2','S6','S9','G1','G2','G6','G9','P1','P2','P3','P4','P5','P6','P7'];body.innerHTML='';cats.forEach(function(k){if(!BB[k])return;var tr=document.createElement('tr'),html='<td><span class="pill p'+BB[k].grp+'">'+k+'</span></td><td>'+BB[k].name+'</td>';[0,1,2,3,5].forEach(function(i){html+='<td class="num"><input class="mw-v16" type="number" min="0" step="1" value="'+Math.round(BB[k].mw[i]||0)+'" data-cat="'+k+'" data-idx="'+i+'"></td>'});html+='<td>'+(BB[k].teil?'Teilstat.':'Vollstat.')+'</td>';tr.innerHTML=html;body.appendChild(tr)});Array.prototype.slice.call(body.querySelectorAll('input')).forEach(function(inp){inp.onchange=function(){var k=this.dataset.cat,i=+this.dataset.idx,v=Math.max(0,Math.round(+this.value||0));BB[k].mw[i]=v;if(k==='A1'||k==='WAN'){BB.A1.mw[i]=v;BB.WAN.mw[i]=v;ruleEditor()}if(typeof onCfgChange==='function')onCfgChange();if(typeof calcPsyScenario==='function')calcPsyScenario();scheduleSave()}})}
function presetButtons(){var wrap=document.querySelector('.psy-presets');if(!wrap)return;var bs=Array.prototype.slice.call(wrap.querySelectorAll('button'));bs.forEach(function(b,i){b.classList.add(i===0?'v16-base':'v16-comp');b.addEventListener('click',function(){bs.forEach(function(x){x.classList.remove('v16-active')});b.classList.add('v16-active');scheduleSave()})})}
function dataCard(){var page=id('page-cfg');if(!page||id('v16-data'))return;var cards=page.querySelectorAll('.card');if(!cards.length)return;var c=document.createElement('div');c.className='card';c.id='v16-data';c.innerHTML='<div class="card-head"><span class="card-title">Datenverwaltung</span><span class="card-sub">lokal im Browser · Export/Import möglich</span></div><div class="card-body"><div class="data-actions"><button class="btn btn-sm btn-save" id="v16-save">Jetzt speichern</button><button class="btn btn-sm btn-export" id="v16-export">Planung exportieren</button><button class="btn btn-sm btn-import" id="v16-import">Planung importieren</button><button class="btn btn-sm btn-reset" id="v16-reset">Ausgangswerte wiederherstellen</button><input id="v16-file" type="file" accept=".json,application/json" style="display:none"><span class="data-status" id="v16-status">Noch nicht gespeichert</span></div><div class="alert a-info" style="margin-top:10px">Die Planung wird automatisch in diesem Browser gespeichert. Zur Weitergabe bitte die JSON-Datei exportieren.</div></div>';cards[0].parentNode.insertBefore(c,cards[0].nextSibling);id('v16-save').onclick=function(){save(true)};id('v16-export').onclick=exportState;id('v16-import').onclick=function(){id('v16-file').click()};id('v16-file').onchange=importState;id('v16-reset').onclick=resetState}
function state(){var mins={};Object.keys(BB).forEach(function(k){mins[k]=BB[k].mw.slice()});return{schema:'PPP-RL-Planer',version:'16.2',savedAt:new Date().toISOString(),klinik:clone(KLINIK),minutes:mins,fehl:typeof FEHL!=='undefined'?clone(FEHL):null,eq:typeof EQ_ZIEL!=='undefined'?EQ_ZIEL:null,bd:typeof IB_BD!=='undefined'?IB_BD:null,psy:typeof PSY!=='undefined'?clone(PSY):null}}
function status(t){var e=id('v16-status');if(e)e.textContent=t}
function apply(x){if(!x||x.schema!=='PPP-RL-Planer')throw Error('Ungültige Planungsdatei');loading=true;try{if(x.klinik){['vs','tk'].forEach(function(g){(x.klinik[g]||[]).forEach(function(a,i){if(!KLINIK[g][i])return;KLINIK[g][i].name=a.name;KLINIK[g][i].betten=Math.max(1,Math.round(+a.betten||1));Object.keys(KLINIK[g][i].mix).forEach(function(k){KLINIK[g][i].mix[k]=0});Object.keys(a.mix||{}).forEach(function(k){if(k in KLINIK[g][i].mix)KLINIK[g][i].mix[k]=Math.max(0,Math.round(+a.mix[k]||0))})})})}if(x.minutes){Object.keys(x.minutes).forEach(function(k){if(BB[k])BB[k].mw=x.minutes[k].slice()})}BB.WAN.mw=BB.A1.mw.slice();if(KLINIK.vs[10])delete KLINIK.vs[10].mix.WAN;if(KLINIK.vs[11])delete KLINIK.vs[11].mix.WAN;if(x.fehl&&typeof FEHL!=='undefined')Object.keys(FEHL).forEach(function(k){if(x.fehl[k]!==undefined)FEHL[k]=+x.fehl[k]});if(x.eq!==null&&typeof EQ_ZIEL!=='undefined')EQ_ZIEL=+x.eq;if(x.bd!==null&&typeof IB_BD!=='undefined')IB_BD=+x.bd;if(x.psy&&typeof PSY!=='undefined')PSY=x.psy;rebuild();ruleEditor();if(typeof onCfgChange==='function')onCfgChange();if(typeof calcPsyScenario==='function')calcPsyScenario()}finally{loading=false}}
function save(manual){if(loading)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state()));status((manual?'Manuell gespeichert · ':'Gespeichert · ')+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}))}catch(e){status('Speichern fehlgeschlagen')}}
function scheduleSave(){if(loading)return;clearTimeout(saveTimer);saveTimer=setTimeout(function(){save(false)},250)}
function load(){try{var r=localStorage.getItem(STORAGE_KEY);if(!r){status('Ausgangswerte · noch nicht gespeichert');return false}apply(JSON.parse(r));status('Lokale Planung geladen');return true}catch(e){console.error(e);status('Lokale Daten konnten nicht geladen werden');return false}}
function exportState(){var b=new Blob([JSON.stringify(state(),null,2)],{type:'application/json'}),a=document.createElement('a'),d=new Date().toISOString().slice(0,10);a.href=URL.createObjectURL(b);a.download='PPP-RL_Planung_'+d+'.json';document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove()},100);status('Planung exportiert')}
function importState(e){var f=e.target.files&&e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{apply(JSON.parse(r.result));save(false);status('Importiert: '+f.name)}catch(x){alert('Die Datei konnte nicht importiert werden.')}e.target.value=''};r.readAsText(f)}
function resetState(){if(!defaults||!confirm('Alle aktuellen Eingaben durch die Ausgangswerte ersetzen?'))return;localStorage.removeItem(STORAGE_KEY);apply(clone(defaults));save(false);status('Auf Ausgangswerte zurückgesetzt')}
function summary(){if(typeof calcCfgSummary!=='function')return;var old=calcCfgSummary;calcCfgSummary=function(){old();var kae=[0,1,2,3,4,5,6,7,8,9,10,11],pkf=[12,13,14,15],pc=['P1','P2','P3','P4','P5'];function sum(arr,fn){return arr.reduce(function(a,i){return a+fn(KLINIK.vs[i])},0)}function real(st){return Object.keys(st.mix).reduce(function(a,k){return a+(+st.mix[k]||0)},0)}function psy(st){return pc.reduce(function(a,k){return a+(+st.mix[k]||0)},0)}var kr=sum(kae,real),pr=sum(pkf,real),kp=sum(kae,psy),pp=sum(pkf,psy),kw=sum(kae,function(st){return+st.mix.WAN||0}),pw=sum(pkf,function(st){return+st.mix.WAN||0}),tr=KLINIK.tk.reduce(function(a,st){return a+real(st)},0),tc=KLINIK.tk.reduce(function(a,st){return a+(+st.betten||0)},0),cap=id('cfg-cap-kpis');if(cap)cap.innerHTML=kpi('KAE Erlangen',f1(kr-kp)+' Patienten','ohne P1–P5','blue')+kpi('PKF Fürth',f1(pr-pp)+' Patienten','ohne P1–P5','purple')+kpi('Tageskliniken',f1(tr)+' / '+f0(tc),'Ø belegt / Plätze · '+f1(tc?tr/tc*100:0)+' %','ok')+kpi('WAN',f0(kw+pw)+' Patienten','KAE '+f0(kw)+' · PKF '+f0(pw)+' · keine TK','purple')+kpi('Psychosomatik',f0(kp+pp)+' Patienten','Summe P1–P5','blue')}}}
function labels(){document.title='PPP-RL 2027 · Klinikplanung v16.2';var h=document.querySelector('.header-mid');if(h)h.textContent='Klinikplanung 2027 · Psychiatrie & Psychosomatik · v16.2';var live=document.querySelector('.chip.live');if(live)live.textContent='v16.2'}
function init(){if(initDone)return;if(typeof BB==='undefined'||typeof KLINIK==='undefined'||typeof buildAllCards!=='function'){setTimeout(init,100);return}initDone=true;addStyle();removeScenarios();setupWAN();summary();rebuild();ruleEditor();presetButtons();labels();dataCard();defaults=state();if(!load()){if(typeof calcCfgSummary==='function')calcCfgSummary()}ensureAccordion();document.addEventListener('change',function(e){if(e.target&&e.target.matches('input,select'))scheduleSave()});document.addEventListener('input',function(e){if(e.target&&e.target.matches('input[type=number],input[type=range],input[type=text]'))scheduleSave()});window.addEventListener('pagehide',function(){save(false)})}
init();
})();